### ISSUE TITLE
Why do we need the PseudoOrder type?

### ISSUE THREAD

**Issue by GalateaTom** [galatea-associates/gerrard-sl#22]
https://github.com/galatea-associates/gerrard-sl/blob/8cc9ab511444a5cd79930b5151b71e825f9d0c90/src/main/java/Agreements/Exchange.java#L116

**Comment by Gala-Gerrard** [comment]
PseduoOrder is used after the lastExecutedPrice changes, so that the triggerPrices of Stop Orders are checked to see if any new orders have been activated. A duplicate order is created with an FOK value for Time In Force and is inputted into the exchange, which ensures that the order is not readded to the exchange if no matches are found and also ensures that the chronological sequence of orders is maintained

**Comment by GalateaTom** [comment]
Ok.  Please javadoc the createPseudoOrder method to say that this is why it exists
